### ISSUE TITLE
Support utf8

### ISSUE THREAD

**Issue by lefoyer** [bluec0re/python-wcfbin#10]
Error encode binaryxml with utf8 symbols.

Sample file:
https://www.dropbox.com/s/1i6tuztv2tx7lpz/re4.bin?dl=0

Errors:
./wcf2xml.py re4 >re4.xml
Traceback (most recent call last):
  File "./wcf2xml.py", line 44, in <module>
    print_records(records)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 68, in print_records
    new_line = print_records(r.childs, skip+1, fp, False)
  File "/home/python-wcfbin/wcf/records/**init**.py", line 64, in print_records
    fp.write(str(r))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

**Comment by lefoyer** [comment]
Sorry problem only on Python 2.7.9, on Python 3.4.2 no problem.
