### ISSUE TITLE
KeyError exceptions when parsing the example WCF dump

### ISSUE THREAD

**Issue by v-p-b** [bluec0re/python-wcfbin#11]
I'm trying the code on the packet dump included in the blog post:

https://insinuator.net/2016/08/pentesting-webservices-with-net-tcp-binding/

I've exported the packet from 0x141 to a binary file:

```
python -c 'import binascii; print binascii.unhexlify("06db010056020b0173040b0161065608440a1e0082ab01400a41637469766974794964040d436f7272656c6174696f6e4964982436393837373766652d653637322d346163322d623163642d623962373464313437396538083d687474703a2f2f736368656d61732e6d6963726f736f66742e636f6d2f323030342f30392f536572766963654d6f64656c2f446961676e6f7374696373b1bef9db6d9c998b4e9a140ebf2d6941a24412adf843211e834c8f4e8f0ce47db9cf3a67440c1e0082ab1401560e42030a054207990e596f7520656e74657265643a2030010101"),'  > test.bin
```

Running `wcf2bin.py test.bin` gives the following error:

```
Traceback (most recent call last):
  File "wcf2xml.py", line 43, in <module>
    records = Record.parse(fp)
  File ".../python-wcfbin/wcf/records/base.py", line 111, in parse
    obj = Record.records[type].parse(fp)
  File ".../python-wcfbin/wcf/records/attributes.py", line 174, in parse
    value = Record.records[type].parse(fp)
KeyError: 0
```
Even if I add exception handling to the affected parts of the code KeyErrors pop up at other parts of the application, that indicates that this is not a bug, but more like a user error... What am I missing?

**Comment by bluec0re** [comment]
1. Your conversion line adds an additional newline at the end of the test.bin file.
2. The data you are trying to decode contains not only the binary xml part, but also the net.tcp protocol:
```
NET.TCP
    00000141  06db 01
BINARY XML
                     00 5602 0b01 7304 0b01 6106 5608 ....V...s...a.V.
    00000151  440a 1e00 82ab 0140 0a41 6374 6976 6974 D......@.Activit
    00000161  7949 6404 0d43 6f72 7265 6c61 7469 6f6e yId..Correlation
    00000171  4964 9824 3639 3837 3737 6665 2d65 3637 Id.$6987 77fee67
    00000181  322d 3461 6332 2d62 3163 642d 6239 6237 2-4ac2b1cdb9b7
    00000191  3464 3134 3739 6538 083d 6874 7470 3a2f 4d1479e8.=http:/
    000001A1  2f73 6368 656d 6173 2e6d 6963 726f 736f /schemas .microso
    000001B1  6674 2e63 6f6d 2f32 3030 342f 3039 2f53 ft.com/2004/09/S
    000001C1  6572 7669 6365 4d6f 6465 6c2f 4469 6167 erviceModel/Diag
    000001D1  6e6f 7374 6963 73b1 bef9 db6d 9c99 8b4e nostics....m...N
    000001E1  9a14 0ebf 2d69 41a2 4412 adf8 4321 1e83 ....-iA.D...C!..
    000001F1  4c8f 4e8f 0ce4 7db9 cf3a 6744 0c1e 0082 L.N...}..:gD....
    00000201  ab14 0156 0e42 030a 0542 0799 0e59 6f75 ...V.B...B...You
    00000211  2065 6e74 6572 6564 3a20 3001 0101       entered: 0...
```
The ``06`` stands for [SizedEnvelopedMessageRecord](https://github.com/ernw/net.tcp-proxy/blob/master/nettcp/nmf.py#L350), together with a size field (``db01`` decoded to 219).

3. The following payload (the binary xml data) is an optimized one. It is used during a stateful conversation and both peers built a dynamic dictionary over all received strings. So if you do this (the ``00`` byte means that no additional strings need to be added to the dictionary):

```
echo "56020b0173040b0161065608440a1e0082ab01400a41637469766974794964040d436f7272656c6174696f6e4964982436393837373766652d653637322d346163322d623163642d623962373464313437396538083d687474703a2f2f736368656d61732e6d6963726f736f66742e636f6d2f323030342f30392f536572766963654d6f64656c2f446961676e6f7374696373b1bef9db6d9c998b4e9a140ebf2d6941a24412adf843211e834c8f4e8f0ce47db9cf3a67440c1e0082ab1401560e42030a054207990e596f7520656e74657265643a2030010101" | xxd -r -p > test.bin
```

You'll get

```
Traceback (most recent call last):
  File "./wcf2xml.py", line 45, in <module>
    records = Record.parse(fp)
  File "/home/bluec0re/sources/python-wcfbin/wcf/records/base.py", line 111, in parse
    obj = Record.records[type].parse(fp)
  File "/home/bluec0re/sources/python-wcfbin/wcf/records/elements.py", line 169, in parse
    return cls(index)
  File "/home/bluec0re/sources/python-wcfbin/wcf/records/elements.py", line 137, in __init__
    self.name = dictionary[self.index]
KeyError: 3
```

Investigating the previous message

```
    00000001  06bd 025f 2c68 7474 703a 2f2f 7465 6d70 ..._,http://temp
    00000011  7572 692e 6f72 672f 4953 6572 7669 6365 uri.org/IService
    00000021  312f 4765 7444 6174 6152 6573 706f 6e73 1/GetDataRespons
    00000031  650f 4765 7444 6174 6152 6573 706f 6e73 e.GetDataRespons
    00000041  6513 6874 7470 3a2f 2f74 656d 7075 7269 e.http://tempuri
    00000051  2e6f 7267 2f0d 4765 7444 6174 6152 6573 .org/.GetDataRes
    00000061  756c 7456 020b 0173 040b 0161 0656 0844 ultV...s...a.V.D
    00000071  0a1e 0082 ab01 400a 4163 7469 7669 7479 ......@.Activity
    00000081  4964 040d 436f 7272 656c 6174 696f 6e49 Id..CorrelationI
    00000091  6498 2436 3038 3538 3730 642d 3835 3264 d.$6085870d852d
    000000A1  2d34 6236 322d 3931 6437 2d61 3563 6334 -4b6291d7a5cc4
    000000B1  3530 3361 3635 3808 3d68 7474 703a 2f2f 503a658.=http://
    000000C1  7363 6865 6d61 732e 6d69 6372 6f73 6f66 schemas.microsof
    000000D1  742e 636f 6d2f 3230 3034 2f30 392f 5365 t.com/2004/09/Se
    000000E1  7276 6963 654d 6f64 656c 2f44 6961 676e rviceModel/Diagn
    000000F1  6f73 7469 6373 b167 9317 e29b 145e 4685 ostics.g.....^F.
    00000101  3657 8293 1d6b 8644 12ad 9ddf 13ad aa57 6W...k.D.......W
    00000111  0140 8fe2 2830 d9d9 e8e7 440c 1e00 82ab .@..(0....D.....
    00000121  1401 560e 4203 0a05 4207 9911 596f 7520 ..V.B...B...You 
    00000131  656e 7465 7265 643a 2031 3333 3701 0101 entered: 1337...
```

shows that ``5f`` bytes are used to transmit a dictionary.

```
    00000001            2c68 7474 703a 2f2f 7465 6d70 ..._,http://temp
    00000011  7572 692e 6f72 672f 4953 6572 7669 6365 uri.org/IService
    00000021  312f 4765 7444 6174 6152 6573 706f 6e73 1/GetDataRespons
    00000031  650f 4765 7444 6174 6152 6573 706f 6e73 e.GetDataRespons
    00000041  6513 6874 7470 3a2f 2f74 656d 7075 7269 e.http://tempuri
    00000051  2e6f 7267 2f0d 4765 7444 6174 6152 6573 .org/.GetDataRes
    00000061  756c 74                                 ult
```

This can be split into
* http://tempuri.org/IService1/GetDataResponse [index 1]
* GetDataResponse [index 3]
* http://tempuri.org/ [index 5]
* GetDataResult [index 7]

This means that you at least know that it tried to reference GetDataResponse somewhere. To get the full xml output, you could either
* patch the dictionary in this library to reflect the dynamic values
or
* create a [trace file](https://github.com/ernw/python-wcfbin/files/1091504/trace.txt) file for the [net.tcp library](https://github.com/ernw/net.tcp-proxy)

Doing the 2nd option would result in
```
$ decode-wcfbin.py /tmp/trace.txt
[0000-00-00 00:00:00] {?} c>s
#############################
VersionRecord(MajorVersion=1, MinorVersion=0)

[0000-00-00 00:00:00] {?} c>s
#############################
ModeRecord(Mode=Mode.DUPLEX)

[0000-00-00 00:00:00] {?} c>s
#############################
ViaRecord(ViaLength=36, Via='net.tcp://192.168.56.1:8523/Service1')

[0000-00-00 00:00:00] {?} c>s
#############################
KnownEncodingRecord(Encoding=KnownEncoding.BINARY_DICT)

[0000-00-00 00:00:00] {?} c>s
#############################
PreambleEndRecord()

[0000-00-00 00:00:00] {?} s>c
#############################
PreambleAckRecord()

[0000-00-00 00:00:00] {?} c>s
#############################
SizedEnvelopedMessageRecord(Size=176, Payload=b'l$http://tempuri.org/IService1/GetData$net.tcp://192.168.56.1:8523/Service1\x07GetData\x13http://tempuri.org/\x05valueV\x02\x0b\x01s\x04\x0b\x01a\x06V\x08D\n\x1e\x00\x82\xab\x01D\x1a\xad\x9d\xdf\x13\xad\xaaW\x01@\x8f\xe2(0\xd9\xd9\xe8\xe7D,D*\xab\x14\x01D\x0c\x1e\x00\x82\xab\x03\x01V\x0eB\x05\n\x07B\t\x8b9\x05\x01\x01\x01')

Dictionary table: 108 bytes
1: http://tempuri.org/IService1/GetData
3: net.tcp://192.168.56.1:8523/Service1
5: GetData
7: http://tempuri.org/
9: value
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
 <s:Header>
  <a:Action s:mustUnderstand="1">http://tempuri.org/IService1/GetData</a:Action>
  <a:MessageID>urn:uuid:ad13df9d-57aa-4001-8fe2-2830d9d9e8e7</a:MessageID>
  <a:ReplyTo>
   <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
  </a:ReplyTo>
  <a:To s:mustUnderstand="1">net.tcp://192.168.56.1:8523/Service1</a:To>
 </s:Header>
 <s:Body>
  <GetData xmlns="http://tempuri.org/">
   <value>1337</value>
  </GetData>
 </s:Body>
</s:Envelope>


[0000-00-00 00:00:00] {?} s>c
#############################
SizedEnvelopedMessageRecord(Size=317, Payload=b'_,http://tempuri.org/IService1/GetDataResponse\x0fGetDataResponse\x13http://tempuri.org/\rGetDataResultV\x02\x0b\x01s\x04\x0b\x01a\x06V\x08D\n\x1e\x00\x82\xab\x01@\nActivityId\x04\rCorrelationId\x98$6085870d-852d-4b62-91d7-a5cc4503a658\x08=http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics\xb1g\x93\x17\xe2\x9b\x14^F\x856W\x82\x93\x1dk\x86D\x12\xad\x9d\xdf\x13\xad\xaaW\x01@\x8f\xe2(0\xd9\xd9\xe8\xe7D\x0c\x1e\x00\x82\xab\x14\x01V\x0eB\x03\n\x05B\x07\x99\x11You entered: 1337\x01\x01\x01')

Dictionary table: 95 bytes
1: http://tempuri.org/IService1/GetDataResponse
3: GetDataResponse
5: http://tempuri.org/
7: GetDataResult
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
 <s:Header>
  <a:Action s:mustUnderstand="1">http://tempuri.org/IService1/GetDataResponse</a:Action>
  <ActivityId CorrelationId="6085870d-852d-4b62-91d7-a5cc4503a658" xmlns="http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics">e2179367-149b-465e-8536-5782931d6b86</ActivityId>
  <a:RelatesTo>urn:uuid:ad13df9d-57aa-4001-8fe2-2830d9d9e8e7</a:RelatesTo>
  <a:To s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/anonymous</a:To>
 </s:Header>
 <s:Body>
  <GetDataResponse xmlns="http://tempuri.org/">
   <GetDataResult>You entered: 1337</GetDataResult>
  </GetDataResponse>
 </s:Body>
</s:Envelope>


[0000-00-00 00:00:00] {?} c>s
#############################
SizedEnvelopedMessageRecord(Size=66, Payload=b'\x00V\x02\x0b\x01s\x04\x0b\x01a\x06V\x08D\n\x1e\x00\x82\xab\x01D\x1a\xad\xf8C!\x1e\x83L\x8fN\x8f\x0c\xe4}\xb9\xcf:gD,D*\xab\x14\x01D\x0c\x1e\x00\x82\xab\x03\x01V\x0eB\x05\n\x07B\t\x81\x01\x01\x01')

Dictionary table: 0 bytes
1: http://tempuri.org/IService1/GetData
3: net.tcp://192.168.56.1:8523/Service1
5: GetData
7: http://tempuri.org/
9: value
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
 <s:Header>
  <a:Action s:mustUnderstand="1">http://tempuri.org/IService1/GetData</a:Action>
  <a:MessageID>urn:uuid:1e2143f8-4c83-4e8f-8f0c-e47db9cf3a67</a:MessageID>
  <a:ReplyTo>
   <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
  </a:ReplyTo>
  <a:To s:mustUnderstand="1">net.tcp://192.168.56.1:8523/Service1</a:To>
 </s:Header>
 <s:Body>
  <GetData xmlns="http://tempuri.org/">
   <value>0</value>
  </GetData>
 </s:Body>
</s:Envelope>


[0000-00-00 00:00:00] {?} s>c
#############################
SizedEnvelopedMessageRecord(Size=219, Payload=b'\x00V\x02\x0b\x01s\x04\x0b\x01a\x06V\x08D\n\x1e\x00\x82\xab\x01@\nActivityId\x04\rCorrelationId\x98$698777fe-e672-4ac2-b1cd-b9b74d1479e8\x08=http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics\xb1\xbe\xf9\xdbm\x9c\x99\x8bN\x9a\x14\x0e\xbf-iA\xa2D\x12\xad\xf8C!\x1e\x83L\x8fN\x8f\x0c\xe4}\xb9\xcf:gD\x0c\x1e\x00\x82\xab\x14\x01V\x0eB\x03\n\x05B\x07\x99\x0eYou entered: 0\x01\x01\x01')

Dictionary table: 0 bytes
1: http://tempuri.org/IService1/GetDataResponse
3: GetDataResponse
5: http://tempuri.org/
7: GetDataResult
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
 <s:Header>
  <a:Action s:mustUnderstand="1">http://tempuri.org/IService1/GetDataResponse</a:Action>
  <ActivityId CorrelationId="698777fe-e672-4ac2-b1cd-b9b74d1479e8" xmlns="http://schemas.microsoft.com/2004/09/ServiceModel/Diagnostics">6ddbf9be-999c-4e8b-9a14-0ebf2d6941a2</ActivityId>
  <a:RelatesTo>urn:uuid:1e2143f8-4c83-4e8f-8f0c-e47db9cf3a67</a:RelatesTo>
  <a:To s:mustUnderstand="1">http://www.w3.org/2005/08/addressing/anonymous</a:To>
 </s:Header>
 <s:Body>
  <GetDataResponse xmlns="http://tempuri.org/">
   <GetDataResult>You entered: 0</GetDataResult>
  </GetDataResponse>
 </s:Body>
</s:Envelope>


[0000-00-00 00:00:00] {?} c>s
#############################
EndRecord()

[0000-00-00 00:00:00] {?} s>c
#############################
EndRecord()
```

**Comment by v-p-b** [comment]
Thank you for the exhaustive answer!

**Comment by j4s0nmo0n** [comment]
Hello @v-p-b,  

I have the same issue and I suspect the amount of data received. Did you find a solution? Did you patch the dictionary?

Regards
