### ISSUE TITLE
Possible false interpretation

### ISSUE THREAD

**Issue by shidh** [bluec0re/python-wcfbin#9]
i have met one problem "Possible false interpretation" when i call    wcf2xml.py  file.svc, which leads the xml result doesn't work.

I'm not sure i understand the code, why it doesn't work for Decimal interpretation?
datatypes.py:181

**Comment by bluec0re** [comment]
Do you have any more information? A sample file for example? What did you expected and what happened?

**Comment by shidh** [comment]
Hi  @bluec0re ,

thanks for replying. Really appreciate for your help!

If i run the script **python3 wcf2xml.py request.svc > request.xml** , i got warning message:
_WARNING:wcf.datatypes:Possible false interpretation_
....

As github doesn't allowed to upload svc file format, please check **request.txt** for the file **request.svc** i mentioned. [request.txt](https://github.com/ernw/python-wcfbin/files/376090/euRQ.txt)

And when i try to send request with request.xml to sever, i got got error response, which means the request is not in right format.

Below is the error response from server when i post the request.xml.

_<Message>Element 'http://schemas.datacontract.org/2004/07/NewHotel.Contracts:Id' contains data from a type that maps to the name ':mustUnderstand'. The deserializer has no knowledge of any type that maps to this name. Consider using a DataContractResolver or add the type corresponding to 'mustUnderstand' to the list of known types - for example, by using the KnownTypeAttribute attribute or by adding it to the list of known types passed to DataContractSerializer.</Message>
                        <StackTrace>   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract&amp; dataContract)
                            at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, String name, String ns)
                            at ReadRoomTypePriceContractFromXml(XmlReaderDelegator , XmlObjectSerializerReadContext , XmlDictionaryString[] , XmlDictionaryString[] )
                            at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
                            at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract&amp; dataContract)
                            at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, String name, String ns)
                            at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
                            at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
                            at System.Runtime.Serialization.DataContractSerializer.ReadObject(XmlDictionaryReader reader, Boolean verifyObjectName)
                            at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.PartInfo.ReadObject(XmlDictionaryReader reader, XmlObjectSerializer serializer)
                            at System.ServiceModel.Dispatcher.DataContractSerializerOperationFormatter.DeserializeParameterPart(XmlDictionaryReader reader, PartInfo part, Boolean isRequest)</StackTrace>
                        <Type>System.Runtime.Serialization.SerializationException</Type>_

**Comment by bluec0re** [comment]
Ok I see.

regarding the "Possible false interpretation":
At the time of writing, I was not really sure about the decoding of the decimal datatype. I tried to implement it based on the specs, but hadn't had any services to test it with. Therefore I've added the warning that someone who's using this library is aware of the fact that this numbers might be wrong (and if so, may report/fix the problem?)

regarding the parsing error:
The library doesn't produce the same xml as the WCF would do, but instead a version which contains some additional meta information to be able to reconstruct the original binary representation as accurrate as possible. The binary representation has some additional datatypes which must be used when constructing a request. The library was originally developed to enable penetration testers to communicate with WCF services which only allow the binary version of SOAP requests. To create a fully compatible xml, it might be helpful to have a XML and a binary representation of the same request generated by WCF.

Disclaimer: I've never developed a WCF service nor did I had access to one which is under my control. The library was originally developed within one week based on the fact that I had to test a WCF service which used this encoding scheme.

**Comment by bluec0re** [comment]
Btw. I've replaced your file with an obfuscated one. The file you've uploaded contained the webservice url and the username and password.

**Comment by shidh** [comment]
i actually missed some information about what i did, i actually didn't not post the xml that generated by wcf2xml.py. What i did is like this:
[do once only] **request.svc**   --_wcf2xml.py_-->  **request.xml** --_edit and replace_ -->    **request_template.xml**

[do each time when required] adjust **request_template.xml**   --_xml2wcf.py_-->  **NewRequest.svc**  and post NewRequest.svc to server.

i posted the modified binary file(NewRequest.svc) to server by modifying the intermediate xml file(request_template.xml), i do this because i want to enable automation operation of my web-service daily.

This actually works like a charm for some other requests, but doesn't work for the one i post. Do you have any hint how can we fix the decimal datatype translation?

**Comment by bluec0re** [comment]
to the decimal: the best option would be to generate requests with different numbers and verify if the decoding/encoding maintains the correct value

to the error: in this case it would be much more helpful to get the original request (obfuscated url & credentials) to compare it to. And maybe also a WSDL for the description of the service.

**Comment by shidh** [comment]
Thanks for more hints, the file request.txt  i mentioned before is actually the original request.

BTW, you can see the WSDL details here:
https://eu.newhotelcloud.com/Newhotel2011/Pms/Services/NewHotelManagement/NewHotelManagement.svc?wsdl
